// Code generated by MockGen. DO NOT EDIT.
// Source: room.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	entity "github.com/tusmasoma/connectHub-backend/entity"
	usecase "github.com/tusmasoma/connectHub-backend/usecase"
)

// MockRoomUseCase is a mock of RoomUseCase interface.
type MockRoomUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockRoomUseCaseMockRecorder
}

// MockRoomUseCaseMockRecorder is the mock recorder for MockRoomUseCase.
type MockRoomUseCaseMockRecorder struct {
	mock *MockRoomUseCase
}

// NewMockRoomUseCase creates a new mock instance.
func NewMockRoomUseCase(ctrl *gomock.Controller) *MockRoomUseCase {
	mock := &MockRoomUseCase{ctrl: ctrl}
	mock.recorder = &MockRoomUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomUseCase) EXPECT() *MockRoomUseCaseMockRecorder {
	return m.recorder
}

// BatchCreateDefaultChannels mocks base method.
func (m *MockRoomUseCase) BatchCreateDefaultChannels(ctx context.Context, workspaceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreateDefaultChannels", ctx, workspaceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchCreateDefaultChannels indicates an expected call of BatchCreateDefaultChannels.
func (mr *MockRoomUseCaseMockRecorder) BatchCreateDefaultChannels(ctx, workspaceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreateDefaultChannels", reflect.TypeOf((*MockRoomUseCase)(nil).BatchCreateDefaultChannels), ctx, workspaceID)
}

// CreateRoom mocks base method.
func (m *MockRoomUseCase) CreateRoom(ctx context.Context, params usecase.CreateRoomParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoom", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRoom indicates an expected call of CreateRoom.
func (mr *MockRoomUseCaseMockRecorder) CreateRoom(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoom", reflect.TypeOf((*MockRoomUseCase)(nil).CreateRoom), ctx, params)
}

// ListMembershipRooms mocks base method.
func (m *MockRoomUseCase) ListMembershipRooms(ctx context.Context, membershipID string) ([]entity.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMembershipRooms", ctx, membershipID)
	ret0, _ := ret[0].([]entity.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMembershipRooms indicates an expected call of ListMembershipRooms.
func (mr *MockRoomUseCaseMockRecorder) ListMembershipRooms(ctx, membershipID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMembershipRooms", reflect.TypeOf((*MockRoomUseCase)(nil).ListMembershipRooms), ctx, membershipID)
}
