// Code generated by MockGen. DO NOT EDIT.
// Source: membership_room.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	entity "github.com/tusmasoma/connectHub-backend/entity"
	repository "github.com/tusmasoma/connectHub-backend/repository"
)

// MockMembershipChannelRepository is a mock of MembershipChannelRepository interface.
type MockMembershipChannelRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMembershipChannelRepositoryMockRecorder
}

// MockMembershipChannelRepositoryMockRecorder is the mock recorder for MockMembershipChannelRepository.
type MockMembershipChannelRepositoryMockRecorder struct {
	mock *MockMembershipChannelRepository
}

// NewMockMembershipChannelRepository creates a new mock instance.
func NewMockMembershipChannelRepository(ctrl *gomock.Controller) *MockMembershipChannelRepository {
	mock := &MockMembershipChannelRepository{ctrl: ctrl}
	mock.recorder = &MockMembershipChannelRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMembershipChannelRepository) EXPECT() *MockMembershipChannelRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMembershipChannelRepository) Create(ctx context.Context, membershipChannel entity.MembershipChannel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, membershipChannel)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMembershipChannelRepositoryMockRecorder) Create(ctx, membershipChannel interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMembershipChannelRepository)(nil).Create), ctx, membershipChannel)
}

// Delete mocks base method.
func (m *MockMembershipChannelRepository) Delete(ctx context.Context, membershipID, channelID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, membershipID, channelID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMembershipChannelRepositoryMockRecorder) Delete(ctx, membershipID, channelID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMembershipChannelRepository)(nil).Delete), ctx, membershipID, channelID)
}

// Get mocks base method.
func (m *MockMembershipChannelRepository) Get(ctx context.Context, membershipID, channelID string) (*entity.MembershipChannel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, membershipID, channelID)
	ret0, _ := ret[0].(*entity.MembershipChannel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockMembershipChannelRepositoryMockRecorder) Get(ctx, membershipID, channelID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockMembershipChannelRepository)(nil).Get), ctx, membershipID, channelID)
}

// List mocks base method.
func (m *MockMembershipChannelRepository) List(ctx context.Context, qcs []repository.QueryCondition) ([]entity.MembershipChannel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, qcs)
	ret0, _ := ret[0].([]entity.MembershipChannel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockMembershipChannelRepositoryMockRecorder) List(ctx, qcs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMembershipChannelRepository)(nil).List), ctx, qcs)
}

// Update mocks base method.
func (m *MockMembershipChannelRepository) Update(ctx context.Context, id string, membershipChannel entity.MembershipChannel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, membershipChannel)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMembershipChannelRepositoryMockRecorder) Update(ctx, id, membershipChannel interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMembershipChannelRepository)(nil).Update), ctx, id, membershipChannel)
}
