// Code generated by MockGen. DO NOT EDIT.
// Source: membership_room.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	entity "github.com/tusmasoma/connectHub-backend/entity"
	repository "github.com/tusmasoma/connectHub-backend/repository"
)

// MockMembershipRoomRepository is a mock of MembershipRoomRepository interface.
type MockMembershipRoomRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMembershipRoomRepositoryMockRecorder
}

// MockMembershipRoomRepositoryMockRecorder is the mock recorder for MockMembershipRoomRepository.
type MockMembershipRoomRepositoryMockRecorder struct {
	mock *MockMembershipRoomRepository
}

// NewMockMembershipRoomRepository creates a new mock instance.
func NewMockMembershipRoomRepository(ctrl *gomock.Controller) *MockMembershipRoomRepository {
	mock := &MockMembershipRoomRepository{ctrl: ctrl}
	mock.recorder = &MockMembershipRoomRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMembershipRoomRepository) EXPECT() *MockMembershipRoomRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMembershipRoomRepository) Create(ctx context.Context, membershipRoom entity.MembershipRoom) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, membershipRoom)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMembershipRoomRepositoryMockRecorder) Create(ctx, membershipRoom interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMembershipRoomRepository)(nil).Create), ctx, membershipRoom)
}

// Delete mocks base method.
func (m *MockMembershipRoomRepository) Delete(ctx context.Context, membershipID, roomID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, membershipID, roomID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMembershipRoomRepositoryMockRecorder) Delete(ctx, membershipID, roomID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMembershipRoomRepository)(nil).Delete), ctx, membershipID, roomID)
}

// Get mocks base method.
func (m *MockMembershipRoomRepository) Get(ctx context.Context, membershipID, roomID string) (*entity.MembershipRoom, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, membershipID, roomID)
	ret0, _ := ret[0].(*entity.MembershipRoom)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockMembershipRoomRepositoryMockRecorder) Get(ctx, membershipID, roomID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockMembershipRoomRepository)(nil).Get), ctx, membershipID, roomID)
}

// List mocks base method.
func (m *MockMembershipRoomRepository) List(ctx context.Context, qcs []repository.QueryCondition) ([]entity.MembershipRoom, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, qcs)
	ret0, _ := ret[0].([]entity.MembershipRoom)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockMembershipRoomRepositoryMockRecorder) List(ctx, qcs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMembershipRoomRepository)(nil).List), ctx, qcs)
}

// Update mocks base method.
func (m *MockMembershipRoomRepository) Update(ctx context.Context, id string, membershipRoom entity.MembershipRoom) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, membershipRoom)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMembershipRoomRepositoryMockRecorder) Update(ctx, id, membershipRoom interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMembershipRoomRepository)(nil).Update), ctx, id, membershipRoom)
}
