// Code generated by MockGen. DO NOT EDIT.
// Source: user_workspace.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	entity "github.com/tusmasoma/connectHub-backend/entity"
	repository "github.com/tusmasoma/connectHub-backend/repository"
)

// MockUserWorkspaceRepository is a mock of UserWorkspaceRepository interface.
type MockUserWorkspaceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserWorkspaceRepositoryMockRecorder
}

// MockUserWorkspaceRepositoryMockRecorder is the mock recorder for MockUserWorkspaceRepository.
type MockUserWorkspaceRepositoryMockRecorder struct {
	mock *MockUserWorkspaceRepository
}

// NewMockUserWorkspaceRepository creates a new mock instance.
func NewMockUserWorkspaceRepository(ctrl *gomock.Controller) *MockUserWorkspaceRepository {
	mock := &MockUserWorkspaceRepository{ctrl: ctrl}
	mock.recorder = &MockUserWorkspaceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserWorkspaceRepository) EXPECT() *MockUserWorkspaceRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserWorkspaceRepository) Create(ctx context.Context, userWorkspace entity.UserWorkspace) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userWorkspace)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserWorkspaceRepositoryMockRecorder) Create(ctx, userWorkspace interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserWorkspaceRepository)(nil).Create), ctx, userWorkspace)
}

// Delete mocks base method.
func (m *MockUserWorkspaceRepository) Delete(ctx context.Context, ID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, ID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserWorkspaceRepositoryMockRecorder) Delete(ctx, ID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserWorkspaceRepository)(nil).Delete), ctx, ID)
}

// Get mocks base method.
func (m *MockUserWorkspaceRepository) Get(ctx context.Context, userID, workspaceID string) (*entity.UserWorkspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID, workspaceID)
	ret0, _ := ret[0].(*entity.UserWorkspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockUserWorkspaceRepositoryMockRecorder) Get(ctx, userID, workspaceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUserWorkspaceRepository)(nil).Get), ctx, userID, workspaceID)
}

// List mocks base method.
func (m *MockUserWorkspaceRepository) List(ctx context.Context, qcs []repository.QueryCondition) ([]entity.UserWorkspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, qcs)
	ret0, _ := ret[0].([]entity.UserWorkspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockUserWorkspaceRepositoryMockRecorder) List(ctx, qcs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUserWorkspaceRepository)(nil).List), ctx, qcs)
}

// Update mocks base method.
func (m *MockUserWorkspaceRepository) Update(ctx context.Context, id string, userWorkspace entity.UserWorkspace) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, userWorkspace)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserWorkspaceRepositoryMockRecorder) Update(ctx, id, userWorkspace interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserWorkspaceRepository)(nil).Update), ctx, id, userWorkspace)
}
